#!/usr/bin/env bash

log() {
    echo -e "\033[0;32m$*\033[0m"
}

die() {
    echo -e "\033[0;31m$*\033[0m"
    exit 1
}

NEW_VERSION="$(cog bump --auto --dry-run)"

if ! [[ "$NEW_VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    die "failed to get a new version"
fi

log "bumping version to '$NEW_VERSION'"
if ! cog bump --auto --annotated "$NEW_VERSION"; then
    die "failed to bump version to '$NEW_VERSION'"
fi
log "bumped version to '$NEW_VERSION'"

log "pushing version to remote"
if ! git push --follow-tags; then
    die "failed to push tags"
fi
log "pushed version to remote"
